name: Build Android App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y zip unzip openjdk-17-jdk

    - name: Install Buildozer
      run: |
        python -m pip install --upgrade pip
        pip install buildozer

    - name: Pre-accept Android SDK licenses
      run: |
        mkdir -p ~/.android
        echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > ~/.android/repositories.cfg
        yes | sdkmanager --licenses

    - name: Install Android SDK components
      run: |
        yes | sdkmanager --install "platform-tools" "platforms;android-33" "build-tools;36.0.0" "cmdline-tools;latest" "ndk;25.1.8937393"

    - name: Build with Buildozer
      run: |
        buildozer android debug
